### ISSUE TITLE
Instructions for using this with firefox?

### ISSUE THREAD

**Issue by jamespsteinberg** [Wolnosciowiec/web-proxy#2]
Hey this is an amazing tool, 

I think you could reach more people if there were instructions on setting up this proxy with firefox or some GUI

**Comment by blackandred** [comment]
Hi,

Thanks, I'm glad you enjoy it.
I will put a task to extend documentation to my list. I'm a little bit wondering if there is a possibility to connect it to Firefox - the web-proxy was designed to be used by applications that are collecting the data or displaying other pages in a iframe (eg. article aggregators showing the source page), I will check this out also.

Originally the web-proxy project is used at the "parent project" in two cases:
- After getting a list of events from Facebook via API, the background images and location data are fetched using it, so there is a feature that detects captcha and returns 500 error which causes load balancer to switch to other instance of web-proxy and continue work on different IP
- "Parent project" is aggregating articles from other pages, when user wants to see the details then a source is rendered in a iframe, but most of the sources do not have SSL, so the web-proxy is helping there by passing throught the traffic and modifying the HTML and CSS to point all of the images, scripts and css through web-proxy (example: https://wolnosciowiec.net/pl/flash , click any article header)

**Comment by blackandred** [comment]
I suggest to create an endpoint with an iframe that would allow to put the url address and navigate. Other thing may be an extension for Firefox. I think you can feel free to submit a PR :)

**Comment by jamespsteinberg** [comment]
Thanks! I was looking for a good web proxy that is simple to deploy on Heroku and this seems the closest I can find that still works. I have to test more but I am not 100% this will work with logging and all cookies though

**Comment by blackandred** [comment]
As it was designed mainly for data crawling it does not have a good support for cookies.
Generally all set-cookie headers should be cutted off because they would be mixed on same domain I think.
